# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id_machine', models.AutoField(primary_key=True, serialize=False)),
                ('machine_name', models.CharField(max_length=200)),
                ('service_interval', models.IntegerField(blank=True, null=True)),
                ('last_service', models.DateField(blank=True, null=True)),
                ('is_operational', models.NullBooleanField()),
                ('notes', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name': 'Maszyna',
                'verbose_name_plural': 'Maszyny',
                'db_table': 'machine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id_machine_type', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('machine_type_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Typ maszyny',
                'verbose_name_plural': 'Typy maszyn',
                'db_table': 'machine_type',
                'managed': False,
            },
        ),
    ]
