# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeDict',
            fields=[
                ('id_se_dict', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('se_dict_name', models.CharField(max_length=200, unique=True)),
                ('base_price', models.FloatField(blank=True, null=True)),
                ('avg_time', models.IntegerField(blank=True, null=True)),
                ('continous', models.BooleanField()),
                ('notes', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name': 'Serwis',
                'verbose_name_plural': 'Slownik serwisow',
                'db_table': 'se_dict',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeDiscount',
            fields=[
                ('id_se_discount', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Znizka na serwis',
                'verbose_name_plural': 'Znizki na serwis',
                'db_table': 'se_discount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeRequirement',
            fields=[
                ('id_se_requirement', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.FloatField(blank=True, null=True)),
                ('activity_sort_order', models.IntegerField(blank=True, null=True)),
                ('activity_name', models.CharField(blank=True, max_length=200, null=True)),
                ('time_minutes', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Wymaganie serwisu',
                'verbose_name_plural': 'Wymagania serwisow',
                'db_table': 'se_requirement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('is_confirmed', models.NullBooleanField(default=False, verbose_name='Powierdzony')),
                ('create_invoice', models.NullBooleanField(default=False, verbose_name='Utworzyc fakture VAT')),
                ('service_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kwota znizki')),
                ('service_discount_percent', models.FloatField(blank=True, null=True, verbose_name='Procent znizki')),
                ('min_start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Szukanie czasu od')),
                ('planned_start', models.DateTimeField(blank=True, null=True, verbose_name='Planowany poczatek')),
                ('planned_end', models.DateTimeField(blank=True, null=True, verbose_name='Planowane zakonczenie')),
                ('real_start', models.DateTimeField(blank=True, null=True, verbose_name='Rzeczywisty poczatek')),
                ('real_end', models.DateTimeField(blank=True, null=True, verbose_name='Rzeczywiste zakonczenie')),
                ('reminder_sms_minutes', models.IntegerField(blank=True, default=-1, null=True, verbose_name='Ilosc minut miedzy SMS a rozpoczeciem')),
                ('reminder_email_minutes', models.IntegerField(blank=True, default=-1, null=True, verbose_name='Ilosc minut miedzy e-mail a rozpoczeciem')),
                ('finished_info_sms', models.NullBooleanField(default=True, verbose_name='SMS o ukonczeniu')),
                ('finished_info_email', models.NullBooleanField(default=True, verbose_name='E-mail o ukonczeniu')),
                ('notes', models.CharField(blank=True, max_length=400, null=True, verbose_name='Uwagi')),
                ('created_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Data utworzenia')),
                ('created_by', models.CharField(blank=True, max_length=10, null=True, verbose_name='Utworzone przez')),
                ('confirmed_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Potwierdzony poczatek uslugi')),
                ('confirmed_by', models.CharField(blank=True, max_length=10, null=True, verbose_name='Potwierdone przez')),
            ],
            options={
                'verbose_name': 'Serwis',
                'verbose_name_plural': 'Lista serwisow',
                'db_table': 'service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceArchived',
            fields=[
                ('id_service_archived', models.AutoField(primary_key=True, serialize=False)),
                ('id_service', models.IntegerField()),
                ('service_code', models.CharField(max_length=10)),
                ('service_name', models.CharField(blank=True, max_length=200, null=True)),
                ('service_discount_amount', models.FloatField(blank=True, null=True)),
                ('service_discount_percent', models.FloatField(blank=True, null=True)),
                ('client', models.IntegerField()),
                ('client_first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('client_last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('client_name', models.CharField(blank=True, max_length=200, null=True)),
                ('client_discount', models.FloatField(blank=True, null=True)),
                ('location', models.IntegerField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=200, null=True)),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('planned_end', models.DateField(blank=True, null=True)),
                ('real_start', models.DateField(blank=True, null=True)),
                ('real_end', models.DateField(blank=True, null=True)),
                ('reminder_sms_minutes', models.IntegerField(blank=True, null=True)),
                ('reminder_email_minutes', models.IntegerField(blank=True, null=True)),
                ('finished_info_sms', models.NullBooleanField()),
                ('finished_info_email', models.NullBooleanField()),
                ('notes', models.CharField(blank=True, max_length=400, null=True)),
                ('created_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=10, null=True)),
                ('is_confirmed', models.NullBooleanField()),
                ('confirmed_datetime', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.CharField(blank=True, max_length=10, null=True)),
                ('is_deleted', models.NullBooleanField()),
                ('deleted_timestamp', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=10, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=400, null=True)),
                ('min_start_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Serwis archiwalny',
                'verbose_name_plural': 'Archiwum serwisow',
                'db_table': 'service_archived',
                'managed': False,
            },
        ),
    ]
