# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clblockedreasondict',
            options={'managed': False, 'verbose_name': 'Powód blokady', 'verbose_name_plural': 'Powody blokady'},
        ),
        migrations.AlterModelOptions(
            name='clcommunicationlog',
            options={'managed': False, 'verbose_name': 'Komunikacja z klientem', 'verbose_name_plural': 'Log komunikacji z klientami'},
        ),
        migrations.AlterModelOptions(
            name='clcommunicationreason',
            options={'managed': False, 'verbose_name': 'Powod komunikacji', 'verbose_name_plural': 'Slownik powodow komunikacji'},
        ),
        migrations.AlterModelOptions(
            name='cldiscount',
            options={'managed': False, 'verbose_name': 'Znizka dla klienta', 'verbose_name_plural': 'Znizki dla klientow'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'managed': True, 'verbose_name': 'Klinet', 'verbose_name_plural': 'Lista klientow'},
        ),
        migrations.AlterModelOptions(
            name='clparams',
            options={'managed': False, 'verbose_name': 'Parametry modulu klienta', 'verbose_name_plural': 'Parametry modulu klienta'},
        ),
        migrations.AlterModelOptions(
            name='clpayment',
            options={'managed': False, 'verbose_name': 'Platnosc klienta', 'verbose_name_plural': 'Platnosci klientow'},
        ),
        migrations.AlterModelOptions(
            name='clpaymentline',
            options={'managed': False, 'verbose_name': 'Linia platnosci klienta', 'verbose_name_plural': 'Linie platnosci klientow'},
        ),
        migrations.AlterModelOptions(
            name='clunconfirmed',
            options={'managed': False, 'verbose_name': 'Niepotwierdzony klient', 'verbose_name_plural': 'Niepotwierdzeni klienci'},
        ),
        migrations.AlterModelOptions(
            name='companybranch',
            options={'managed': False, 'verbose_name': 'Oddzial', 'verbose_name_plural': 'Lista oddzialow'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'managed': False, 'verbose_name': 'Kontakt', 'verbose_name_plural': 'Lista kontakow'},
        ),
        migrations.AlterModelOptions(
            name='contacttype',
            options={'managed': False, 'verbose_name': 'Typ kontaktu', 'verbose_name_plural': 'Slownik typow kontaktu'},
        ),
        migrations.AlterModelOptions(
            name='countrydict',
            options={'managed': False, 'verbose_name': 'Panstwo', 'verbose_name_plural': 'Slownik panstw'},
        ),
        migrations.AlterModelOptions(
            name='currrency',
            options={'managed': False, 'verbose_name': 'Waluta', 'verbose_name_plural': 'Slownik walut'},
        ),
        migrations.AlterModelOptions(
            name='discountdict',
            options={'managed': False, 'verbose_name': 'Znizka', 'verbose_name_plural': 'Slownik znizek'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'managed': False, 'verbose_name': 'Lokalizacja', 'verbose_name_plural': 'Lokalizacje'},
        ),
        migrations.AlterModelOptions(
            name='locationtype',
            options={'managed': False, 'verbose_name': 'Typ lokacji', 'verbose_name_plural': 'Lista typow lokacji'},
        ),
        migrations.AlterModelOptions(
            name='workdaycalendar',
            options={'managed': False, 'verbose_name': 'Kaledarz roboczy', 'verbose_name_plural': 'Kalendarze robocze'},
        ),
        migrations.AlterModelOptions(
            name='workdaycalendarparams',
            options={'managed': False, 'verbose_name': 'Paramatry kalendarza', 'verbose_name_plural': 'Parametry kalendarza'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'managed': False, 'verbose_name': 'Pracownik', 'verbose_name_plural': 'Lista pracownikow'},
        ),
        migrations.AlterModelOptions(
            name='wouser',
            options={'managed': False, 'verbose_name': 'Pracownik - user', 'verbose_name_plural': 'Relacje praconicy - userzy'},
        ),
        migrations.AlterModelOptions(
            name='zipcodesdict',
            options={'managed': False, 'verbose_name': 'Kod pocztowy', 'verbose_name_plural': 'Slownik kodow pocztowych'},
        ),
    ]
