# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClBlockedReasonDict',
            fields=[
                ('id_cl_blocked_reason_dict', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('blocked_reason_name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
            options={
                'db_table': 'cl_blocked_reason_dict',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClCommunicationLog',
            fields=[
                ('id_cl_communication_log', models.AutoField(primary_key=True, serialize=False)),
                ('contact_address', models.CharField(blank=True, max_length=100, null=True)),
                ('message_body', models.TextField(blank=True, null=True)),
                ('minutes_before_action', models.IntegerField(blank=True, null=True)),
                ('notes', models.IntegerField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'cl_communication_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClCommunicationReason',
            fields=[
                ('id_client_communication_reason', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('reason_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'cl_communication_reason',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClDiscount',
            fields=[
                ('id_cl_discount', models.AutoField(primary_key=True, serialize=False)),
                ('company_branch', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'cl_discount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('is_company', models.NullBooleanField()),
                ('client_name', models.CharField(blank=True, max_length=200, null=True)),
                ('nip', models.CharField(blank=True, max_length=11, null=True)),
                ('is_blocked', models.NullBooleanField()),
                ('blocked_notes', models.CharField(blank=True, max_length=400, null=True)),
                ('default_invoice', models.NullBooleanField()),
                ('default_reminder_sms_minutes', models.IntegerField(blank=True, null=True)),
                ('is_confirmed', models.NullBooleanField()),
                ('is_rejected', models.NullBooleanField()),
                ('ip_address', models.CharField(blank=True, max_length=20, null=True)),
                ('default_reminder_email_minutes', models.IntegerField(blank=True, null=True)),
                ('default_finished_info_sms', models.IntegerField(blank=True, null=True)),
                ('default_finished_info_email', models.IntegerField(blank=True, null=True)),
                ('client_discount_percent_sum', models.FloatField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_debt', models.TextField()),
                ('allow_new_no_contact', models.BooleanField()),
                ('default_reminder_sms_minutes', models.IntegerField()),
                ('default_reminder_email_minutes', models.IntegerField()),
                ('default_finished_info_sms', models.BooleanField()),
                ('default_finished_info_email', models.BooleanField()),
                ('max_worktime_wo_conf_minutes', models.IntegerField()),
            ],
            options={
                'db_table': 'cl_params',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClPayment',
            fields=[
                ('id_cl_payment', models.AutoField(primary_key=True, serialize=False)),
                ('is_closed', models.NullBooleanField()),
                ('payment_name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_invoice', models.NullBooleanField()),
                ('invoice_voucher', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('payment_sum', models.TextField(blank=True, null=True)),
                ('paid_amount', models.TextField(blank=True, null=True)),
                ('paid_datetime', models.DateTimeField(blank=True, null=True)),
                ('posted_datetime', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=400, null=True)),
                ('created_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'cl_payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClPaymentLine',
            fields=[
                ('id_cl_payment_line', models.AutoField(primary_key=True, serialize=False)),
                ('text_on_invoice', models.CharField(max_length=200)),
                ('qty', models.FloatField(blank=True, null=True)),
                ('final_price', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cl_payment_line',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClUnconfirmed',
            fields=[
                ('cl_unconfirmed', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('client_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_datetime', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'cl_unconfirmed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyBranch',
            fields=[
                ('id_company_branch', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('is_main', models.NullBooleanField()),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('nip', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'company_branch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id_contact', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('house_no', models.CharField(blank=True, max_length=5, null=True)),
                ('apartment_no', models.CharField(blank=True, max_length=5, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('notes', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id_contact_type', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('contact_type_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'contact_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CountryDict',
            fields=[
                ('country', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'country_dict',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Currrency',
            fields=[
                ('id_currency', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('currency_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('ratio_to_main_currency', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'currrency',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiscountDict',
            fields=[
                ('id_discount_dict', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('discount_name', models.CharField(blank=True, max_length=100, null=True)),
                ('discount_amount', models.FloatField(blank=True, null=True)),
                ('discount_percent', models.FloatField(blank=True, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'discount_dict',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiscountScope',
            fields=[
                ('id_discount_scope', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'discount_scope',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id_location', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('is_operational', models.NullBooleanField()),
                ('notes', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id_location_type', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('location_type_name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('location_capacity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'location_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id_machine', models.AutoField(primary_key=True, serialize=False)),
                ('machine_name', models.CharField(max_length=200)),
                ('service_interval', models.IntegerField(blank=True, null=True)),
                ('last_service', models.DateField(blank=True, null=True)),
                ('is_operational', models.NullBooleanField()),
                ('notes', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'machine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id_machine_type', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('machine_type_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'machine_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResourcesUsage',
            fields=[
                ('id_resources_usage', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'resources_usage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResourcesUsageParams',
            fields=[
                ('allow_using_machine_without_service_days_before_date', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'resources_usage_params',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeDict',
            fields=[
                ('id_se_dict', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('se_dict_name', models.CharField(max_length=200, unique=True)),
                ('base_price', models.TextField(blank=True, null=True)),
                ('avg_time', models.IntegerField(blank=True, null=True)),
                ('continous', models.BooleanField()),
                ('notes', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'se_dict',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeDiscount',
            fields=[
                ('id_se_discount', models.AutoField(primary_key=True, serialize=False)),
                ('company_branch', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'se_discount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeRequirement',
            fields=[
                ('id_se_requirement', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.FloatField(blank=True, null=True)),
                ('activity_sort_order', models.IntegerField(blank=True, null=True)),
                ('activity_name', models.CharField(blank=True, max_length=200, null=True)),
                ('time_minutes', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'se_requirement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.AutoField(primary_key=True, serialize=False)),
                ('is_confirmed', models.NullBooleanField()),
                ('create_invoice', models.NullBooleanField()),
                ('service_discount_amount', models.TextField(blank=True, null=True)),
                ('service_discount_percent', models.FloatField(blank=True, null=True)),
                ('min_start_datetime', models.DateTimeField(blank=True, null=True)),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('planned_end', models.DateField(blank=True, null=True)),
                ('real_start', models.DateField(blank=True, null=True)),
                ('real_end', models.DateField(blank=True, null=True)),
                ('reminder_sms_minutes', models.IntegerField(blank=True, null=True)),
                ('reminder_email_minutes', models.IntegerField(blank=True, null=True)),
                ('finished_info_sms', models.NullBooleanField()),
                ('finished_info_email', models.NullBooleanField()),
                ('notes', models.CharField(blank=True, max_length=400, null=True)),
                ('created_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=10, null=True)),
                ('confirmed_datetime', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceArchived',
            fields=[
                ('id_service_archived', models.AutoField(primary_key=True, serialize=False)),
                ('id_service', models.IntegerField()),
                ('service_code', models.CharField(max_length=10)),
                ('service_name', models.CharField(blank=True, max_length=200, null=True)),
                ('service_discount_amount', models.FloatField(blank=True, null=True)),
                ('service_discount_percent', models.FloatField(blank=True, null=True)),
                ('client', models.IntegerField()),
                ('client_first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('client_last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('client_name', models.CharField(blank=True, max_length=200, null=True)),
                ('client_discount', models.FloatField(blank=True, null=True)),
                ('location', models.IntegerField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=200, null=True)),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('planned_end', models.DateField(blank=True, null=True)),
                ('real_start', models.DateField(blank=True, null=True)),
                ('real_end', models.DateField(blank=True, null=True)),
                ('reminder_sms_minutes', models.IntegerField(blank=True, null=True)),
                ('reminder_email_minutes', models.IntegerField(blank=True, null=True)),
                ('finished_info_sms', models.NullBooleanField()),
                ('finished_info_email', models.NullBooleanField()),
                ('notes', models.CharField(blank=True, max_length=400, null=True)),
                ('created_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=10, null=True)),
                ('is_confirmed', models.NullBooleanField()),
                ('confirmed_datetime', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.CharField(blank=True, max_length=10, null=True)),
                ('is_deleted', models.NullBooleanField()),
                ('deleted_timestamp', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=10, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=400, null=True)),
                ('company_branch', models.CharField(max_length=10)),
                ('min_start_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_archived',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SexDict',
            fields=[
                ('id_sex_dict', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'sex_dict',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeSlotList',
            fields=[
                ('id_time_slot', models.DateTimeField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'time_slot_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeSlotParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot_minutes', models.IntegerField()),
            ],
            options={
                'db_table': 'time_slot_params',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WoAbility',
            fields=[
                ('id_wo_ability', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'wo_ability',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WoAbilityDict',
            fields=[
                ('id_wo_ability_dict', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ability_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'wo_ability_dict',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WoAbilityGroupDict',
            fields=[
                ('id_wo_ablility_group_dict', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ability_group_name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'wo_ability_group_dict',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WoAbsence',
            fields=[
                ('id_wo_absence', models.IntegerField(primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('workdays', models.IntegerField(blank=True, null=True)),
                ('hours', models.FloatField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'wo_absence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WoAbsenceType',
            fields=[
                ('id_wo_absence_type', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('absence_name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
            options={
                'db_table': 'wo_absence_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WoGroup',
            fields=[
                ('id_wo_group', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'wo_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WoGroupDict',
            fields=[
                ('id_wo_group_dict', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('worker_group_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'wo_group_dict',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WoGroupPrivilege',
            fields=[
                ('id_wo_group_privilege', models.AutoField(primary_key=True, serialize=False)),
                ('view_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'wo_group_privilege',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WoNotification',
            fields=[
                ('id_wo_notification', models.AutoField(primary_key=True, serialize=False)),
                ('notification_subject', models.CharField(blank=True, max_length=200, null=True)),
                ('notification_text', models.CharField(blank=True, max_length=400, null=True)),
                ('severity', models.IntegerField(blank=True, null=True)),
                ('marked_as_read', models.NullBooleanField()),
            ],
            options={
                'db_table': 'wo_notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WoPrivilegeDict',
            fields=[
                ('id_wo_privilige_dict', models.IntegerField(primary_key=True, serialize=False)),
                ('privilege_name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
            options={
                'db_table': 'wo_privilege_dict',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WoPrivilegeLevelDict',
            fields=[
                ('id_wo_privilege_level_dict', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'wo_privilege_level_dict',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkdayCalendar',
            fields=[
                ('id_workday_calendar', models.DateField(primary_key=True, serialize=False)),
                ('is_workday', models.BooleanField()),
                ('work_start', models.DateField(blank=True, null=True)),
                ('work_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workday_calendar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkdayCalendarParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_workday_start_time', models.DateField(blank=True, null=True)),
                ('default_workday_end_time', models.DateField(blank=True, null=True)),
                ('default_saturday_start_time', models.DateField(blank=True, null=True)),
                ('default_saturday_end_time', models.DateField(blank=True, null=True)),
                ('default_is_saturday_workday', models.BooleanField()),
            ],
            options={
                'db_table': 'workday_calendar_params',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id_worker', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('worker_title', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.NullBooleanField()),
                ('notes', models.CharField(blank=True, max_length=400, null=True)),
                ('company_branch', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'worker',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WoUser',
            fields=[
                ('app_user', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'wo_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZipCodesDict',
            fields=[
                ('id_zip_codes_dict', models.AutoField(primary_key=True, serialize=False)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'zip_codes_dict',
                'managed': False,
            },
        ),
    ]
