# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBranch',
            fields=[
                ('id_company_branch', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('is_main', models.NullBooleanField()),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('nip', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'verbose_name': 'Oddzial',
                'verbose_name_plural': 'Lista oddzialow',
                'db_table': 'company_branch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id_location', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('is_operational', models.NullBooleanField()),
                ('notes', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name': 'Lokalizacja',
                'verbose_name_plural': 'Lokalizacje',
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id_location_type', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('location_type_name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('location_capacity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Typ lokacji',
                'verbose_name_plural': 'Lista typow lokacji',
                'db_table': 'location_type',
                'managed': False,
            },
        ),
    ]
