# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20171003_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'managed': False, 'verbose_name': 'Maszyna', 'verbose_name_plural': 'Maszyny'},
        ),
        migrations.AlterModelOptions(
            name='machinetype',
            options={'managed': False, 'verbose_name': 'Typ maszyny', 'verbose_name_plural': 'Typy maszyn'},
        ),
        migrations.AlterModelOptions(
            name='resourcesusage',
            options={'managed': False, 'verbose_name': 'Uzycie zasobu', 'verbose_name_plural': 'Wykorzystanie zasobow'},
        ),
        migrations.AlterModelOptions(
            name='resourcesusageparams',
            options={'managed': False, 'verbose_name': 'Parametry modulu wykorzystania zasobow', 'verbose_name_plural': 'Parametry modulu wykorzystania zasobow'},
        ),
        migrations.AlterModelOptions(
            name='sedict',
            options={'managed': False, 'verbose_name': 'Serwis', 'verbose_name_plural': 'Slownik serwisow'},
        ),
        migrations.AlterModelOptions(
            name='sediscount',
            options={'managed': False, 'verbose_name': 'Znizka na serwis', 'verbose_name_plural': 'Znizki na serwis'},
        ),
        migrations.AlterModelOptions(
            name='serequirement',
            options={'managed': False, 'verbose_name': 'Wymaganie serwisu', 'verbose_name_plural': 'Wymagania serwisow'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'managed': False, 'verbose_name': 'Serwis', 'verbose_name_plural': 'Lista serwisow'},
        ),
        migrations.AlterModelOptions(
            name='servicearchived',
            options={'managed': False, 'verbose_name': 'Serwis archiwalny', 'verbose_name_plural': 'Archiwum serwisow'},
        ),
        migrations.AlterModelOptions(
            name='sexdict',
            options={'managed': False, 'verbose_name': 'Plec', 'verbose_name_plural': 'Slownik plci'},
        ),
        migrations.AlterModelOptions(
            name='timeslotlist',
            options={'managed': False, 'verbose_name': 'Sloty czasowe', 'verbose_name_plural': 'Sloty czasowe'},
        ),
        migrations.AlterModelOptions(
            name='timeslotparams',
            options={'managed': False, 'verbose_name': 'Parametry slotow czasowych', 'verbose_name_plural': 'Parametry slotow czasowych'},
        ),
        migrations.AlterModelOptions(
            name='woability',
            options={'managed': False, 'verbose_name': 'Umiejetnosc pracownika', 'verbose_name_plural': 'Umiejetnosci pracownikow'},
        ),
        migrations.AlterModelOptions(
            name='woabilitydict',
            options={'managed': False, 'verbose_name': 'Umiejetnosc', 'verbose_name_plural': 'Slownik umiejetnosci'},
        ),
        migrations.AlterModelOptions(
            name='woabilitygroupdict',
            options={'managed': False, 'verbose_name': 'Grupa umiejetnosci', 'verbose_name_plural': 'Slownik grup umijetnosci'},
        ),
        migrations.AlterModelOptions(
            name='woabsence',
            options={'managed': False, 'verbose_name': 'Absencja pracownika', 'verbose_name_plural': 'Absencje pracownikow'},
        ),
        migrations.AlterModelOptions(
            name='woabsencetype',
            options={'managed': False, 'verbose_name': 'Absencja', 'verbose_name_plural': 'Slownik absencji'},
        ),
        migrations.AlterModelOptions(
            name='wogroup',
            options={'managed': False, 'verbose_name': 'Grupa - pracownik', 'verbose_name_plural': 'Grupy pracownikow'},
        ),
        migrations.AlterModelOptions(
            name='wogroupdict',
            options={'managed': False, 'verbose_name': 'Grupa (nazwa slownikowa)', 'verbose_name_plural': 'Slownik grupy pracownikow'},
        ),
        migrations.AlterModelOptions(
            name='wogroupprivilege',
            options={'managed': False, 'verbose_name': 'Uprawnienie grupy', 'verbose_name_plural': 'Uprawnienia grupy'},
        ),
        migrations.AlterModelOptions(
            name='wonotification',
            options={'managed': False, 'verbose_name': 'Alert pracownika', 'verbose_name_plural': 'Alerty pracownika'},
        ),
        migrations.AlterModelOptions(
            name='woprivilegedict',
            options={'managed': False, 'verbose_name': 'Uprawnienie pracownika', 'verbose_name_plural': 'Slownik uprawnien pracownikow'},
        ),
        migrations.AlterModelOptions(
            name='woprivilegeleveldict',
            options={'managed': False, 'verbose_name': 'Poziom uprawnienia pracownika', 'verbose_name_plural': 'Slownik poziomow uprawnien pracownika'},
        ),
        migrations.AddField(
            model_name='client',
            name='blocked_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.ClBlockedReasonDict'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact',
            field=models.ForeignKey(blank=True, db_column='contact', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.Contact'),
        ),
        migrations.AddField(
            model_name='client',
            name='default_company_branch',
            field=models.ForeignKey(db_column='default_company_branch', default='main', on_delete=django.db.models.deletion.DO_NOTHING, to='clients.CompanyBranch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='sex',
            field=models.ForeignKey(blank=True, db_column='sex', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.SexDict'),
        ),
    ]
