# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WoAbility',
            fields=[
                ('id_wo_ability', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name': 'Umiejetnosc pracownika',
                'verbose_name_plural': 'Umiejetnosci pracownikow',
                'db_table': 'wo_ability',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WoAbilityDict',
            fields=[
                ('id_wo_ability_dict', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ability_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Umiejetnosc',
                'verbose_name_plural': 'Slownik umiejetnosci',
                'db_table': 'wo_ability_dict',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WoAbilityGroupDict',
            fields=[
                ('id_wo_ablility_group_dict', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ability_group_name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Grupa umiejetnosci',
                'verbose_name_plural': 'Slownik grup umijetnosci',
                'db_table': 'wo_ability_group_dict',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WoAbsence',
            fields=[
                ('id_wo_absence', models.IntegerField(primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('workdays', models.IntegerField(blank=True, null=True)),
                ('hours', models.FloatField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name': 'Absencja pracownika',
                'verbose_name_plural': 'Absencje pracownikow',
                'db_table': 'wo_absence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WoAbsenceType',
            fields=[
                ('id_wo_absence_type', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('absence_name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Absencja',
                'verbose_name_plural': 'Slownik absencji',
                'db_table': 'wo_absence_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WoGroup',
            fields=[
                ('id_wo_group', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Grupa - pracownik',
                'verbose_name_plural': 'Grupy pracownikow',
                'db_table': 'wo_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WoGroupDict',
            fields=[
                ('id_wo_group_dict', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('worker_group_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Grupa (nazwa slownikowa)',
                'verbose_name_plural': 'Slownik grupy pracownikow',
                'db_table': 'wo_group_dict',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WoGroupPrivilege',
            fields=[
                ('id_wo_group_privilege', models.AutoField(primary_key=True, serialize=False)),
                ('view_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Uprawnienie grupy',
                'verbose_name_plural': 'Uprawnienia grupy',
                'db_table': 'wo_group_privilege',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WoNotification',
            fields=[
                ('id_wo_notification', models.AutoField(primary_key=True, serialize=False)),
                ('notification_subject', models.CharField(blank=True, max_length=200, null=True)),
                ('notification_text', models.CharField(blank=True, max_length=400, null=True)),
                ('severity', models.IntegerField(blank=True, null=True)),
                ('marked_as_read', models.NullBooleanField()),
            ],
            options={
                'verbose_name': 'Alert pracownika',
                'verbose_name_plural': 'Alerty pracownika',
                'db_table': 'wo_notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WoPrivilegeDict',
            fields=[
                ('id_wo_privilige_dict', models.IntegerField(primary_key=True, serialize=False)),
                ('privilege_name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Uprawnienie pracownika',
                'verbose_name_plural': 'Slownik uprawnien pracownikow',
                'db_table': 'wo_privilege_dict',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WoPrivilegeLevelDict',
            fields=[
                ('id_wo_privilege_level_dict', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Poziom uprawnienia pracownika',
                'verbose_name_plural': 'Slownik poziomow uprawnien pracownika',
                'db_table': 'wo_privilege_level_dict',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id_worker', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('worker_title', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.NullBooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name': 'Pracownik',
                'verbose_name_plural': 'Lista pracownikow',
                'db_table': 'worker',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WoUser',
            fields=[
                ('app_user', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Pracownik - user',
                'verbose_name_plural': 'Relacje pracownicy - userzy',
                'db_table': 'wo_user',
                'managed': False,
            },
        ),
    ]
